version: "3.9"
services:
  mariadb:
    image: "mariadb:${DB_VERSION}"
    container_name: "${DB_NAME}"
    hostname: "${DB_NAME}"
    env_file:
      - ".env"
    environment:
      - "TZ=Asia/Taipei"
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASS}"
      - "MYSQL_DATABASE=${DB_DATABASE}"
    ports:
      - "${DB_PORT}"
    volumes:
      - "mariadb_vol:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always

  vaultwarden:
    image: "vaultwarden/server:${VW_VERSION}"
    container_name: "vaultwarden"
    hostname: "vaultwarden"
    env_file:
      - ".env"
    volumes:
      - "vaultwarden_vol:/data/"
    environment:
      ## Had issues when using single parentheses around the mysql URL as in the plain docker example
      # If your password contains special characters, you will need to use percentage encoding.
      # !   #   $   %   &   '   (   )   *   +   ,   /   :   ;   =   ?   @   [   ]
      # %21 %23 %24 %25 %26 %27 %28 %29 %2A %2B %2C %2F %3A %3B %3D %3F %40 %5B %5D
      - "DATABASE_URL=mysql://${DB_USER}:${DB_PASS}@${DB_NAME}/${DB_DATABASE}"
      - "ADMIN_TOKEN=${VW_ADMIN_TOKEN}"
      - "RUST_BACKTRACE=1"
      - "SIGNUPS_ALLOWED=false"
      - "SHOW_PASSWORD_HINT=false"
    ports:
      - "${VW_PORT}:80"
    restart: always
    depends_on:
      - mariadb

volumes:
  vaultwarden_vol:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${VW_DATAPATH}"
    external: false

  mariadb_vol:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "${DB_DATAPATH}"
    external: false
